import { User, Job, Proposal, Contract, Notification, Skill } from '@/types';

export const INITIAL_SKILLS: Skill[] = [
  { id: 'skill-1', name: 'React', slug: 'react', category: 'Frontend' },
  { id: 'skill-2', name: 'Next.js', slug: 'nextjs', category: 'Frontend' },
  { id: 'skill-3', name: 'TypeScript', slug: 'typescript', category: 'Languages' },
  { id: 'skill-4', name: 'Node.js', slug: 'nodejs', category: 'Backend' },
  { id: 'skill-5', name: 'PostgreSQL', slug: 'postgresql', category: 'Database' },
  { id: 'skill-6', name: 'Prisma ORM', slug: 'prisma', category: 'Database' },
  { id: 'skill-7', name: 'Tailwind CSS', slug: 'tailwind-css', category: 'Frontend' },
  { id: 'skill-8', name: 'Python', slug: 'python', category: 'Languages' },
  { id: 'skill-9', name: 'FastAPI', slug: 'fastapi', category: 'Backend' },
  { id: 'skill-10', name: 'UI/UX Design', slug: 'ui-ux-design', category: 'Design' },
  { id: 'skill-11', name: 'Figma', slug: 'figma', category: 'Design' },
  { id: 'skill-12', name: 'Docker', slug: 'docker', category: 'DevOps' },
  { id: 'skill-13', name: 'Stripe API', slug: 'stripe-api', category: 'Fintech' },
  { id: 'skill-14', name: 'GraphQL', slug: 'graphql', category: 'Backend' },
  { id: 'skill-15', name: 'OpenAI API', slug: 'openai-api', category: 'AI/ML' },
];

export const DEMO_USERS: User[] = [
  {
    id: 'user-client-1',
    email: 'client@gigly.com',
    name: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'CLIENT',
    activeRole: 'CLIENT',
    companyName: 'Apex Fintech Labs',
    companyWebsite: 'https://apexlabs.example.com',
    companyDescription: 'Series A fintech building next-generation algorithmic wealth management tools.',
    totalSpent: 42500,
    totalEarnings: 0,
    rating: 4.95,
    reviewCount: 14,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'user-freelancer-1',
    email: 'freelancer@gigly.com',
    name: 'Alex Rivera',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: 'Principal Full-Stack Engineer & Next.js Specialist',
    bio: '8+ years engineering scalable web applications. Ex-Staff Engineer at Stripe ecosystem partner. Top-rated freelancer specialized in Next.js, Prisma, real-time WebSockets, and Stripe payments.',
    role: 'FREELANCER',
    activeRole: 'FREELANCER',
    hourlyRate: 85,
    location: 'San Francisco, CA (Remote)',
    totalEarnings: 78900,
    totalSpent: 0,
    rating: 5.0,
    reviewCount: 29,
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    skills: [
      { id: 'us-1', userId: 'user-freelancer-1', skillId: 'skill-2', proficiency: 'EXPERT', yearsExperience: 5, skill: INITIAL_SKILLS[1] },
      { id: 'us-2', userId: 'user-freelancer-1', skillId: 'skill-3', proficiency: 'EXPERT', yearsExperience: 6, skill: INITIAL_SKILLS[2] },
      { id: 'us-3', userId: 'user-freelancer-1', skillId: 'skill-6', proficiency: 'EXPERT', yearsExperience: 4, skill: INITIAL_SKILLS[5] },
      { id: 'us-4', userId: 'user-freelancer-1', skillId: 'skill-13', proficiency: 'EXPERT', yearsExperience: 5, skill: INITIAL_SKILLS[12] },
    ]
  },
  {
    id: 'user-dual-1',
    email: 'both@gigly.com',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    title: 'Senior Product Designer & Frontend Architect',
    bio: 'Passionate about crafting frictionless human interfaces. I hire top backend developers for my studio and freelance on high-impact design system projects.',
    role: 'BOTH',
    activeRole: 'CLIENT',
    hourlyRate: 95,
    companyName: 'Rostova Studio',
    companyWebsite: 'https://rostovastudio.example.com',
    companyDescription: 'Boutique design & frontend agency based in Zurich.',
    totalEarnings: 34000,
    totalSpent: 28000,
    rating: 4.9,
    reviewCount: 19,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  }
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-1',
    clientId: 'user-client-1',
    title: 'Full-Stack Next.js Developer for AI Copilot Dashboard',
    description: `We are seeking an elite Next.js (App Router) developer to build out our AI financial copilot interface.\n\nKey responsibilities:\n- Implement responsive UI components using Tailwind CSS and React 18/19 server components.\n- Integrate streaming AI chat completions via OpenAI SDK / Vercel AI SDK.\n- Set up PostgreSQL schema with Prisma ORM and secure role-based authentication.\n- Implement real-time updates for telemetry graphs.\n\nRequirements:\n- 3+ years experience with Next.js and TypeScript.\n- Deep understanding of server-side data fetching and optimistic UI patterns.\n- Proven track record with fintech or dashboard architectures.`,
    category: 'Web Development',
    budgetType: 'FIXED',
    budgetAmount: 4500,
    estimatedDuration: '1 to 2 months',
    deadline: new Date(Date.now() + 30 * 86400000).toISOString(),
    requiredSkills: ['Next.js', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Prisma ORM'],
    status: 'OPEN',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    client: DEMO_USERS[0],
    _count: { proposals: 4 },
  },
  {
    id: 'job-2',
    clientId: 'user-dual-1',
    title: 'Stripe Connect Escrow Payment Gateway Integration',
    description: `Need an experienced backend architect to engineer a compliant Stripe Connect Custom/Express escrow payment workflow.\n\nDeliverables:\n- Stripe onboarding flow for marketplace sellers\n- Escrow hold on job contract creation\n- Programmatic milestone releases and webhooks\n- Dispute handling and refund triggers\n\nSecurity and idempotency are top priorities.`,
    category: 'Backend & APIs',
    budgetType: 'FIXED',
    budgetAmount: 3200,
    estimatedDuration: '2 to 4 weeks',
    deadline: new Date(Date.now() + 20 * 86400000).toISOString(),
    requiredSkills: ['Node.js', 'Stripe API', 'TypeScript', 'PostgreSQL'],
    status: 'OPEN',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    client: DEMO_USERS[2],
    _count: { proposals: 2 },
  },
  {
    id: 'job-3',
    clientId: 'user-client-1',
    title: 'High-Frequency Real-time WebSockets Notification Engine',
    description: `Looking for a specialist to build our notification cluster using Socket.io and Redis adapter. Must support 100k concurrent active connections with sub-50ms message latency, fallbacks, and presence tracking.`,
    category: 'DevOps & Architecture',
    budgetType: 'HOURLY',
    budgetMin: 70,
    budgetMax: 110,
    estimatedDuration: '1 to 3 months',
    deadline: new Date(Date.now() + 45 * 86400000).toISOString(),
    requiredSkills: ['Node.js', 'Docker', 'TypeScript', 'PostgreSQL'],
    status: 'OPEN',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    client: DEMO_USERS[0],
    _count: { proposals: 5 },
  },
  {
    id: 'job-4',
    clientId: 'user-dual-1',
    title: 'Modern UI/UX Design System for B2B SaaS in Figma',
    description: `We need a comprehensive Figma design system containing 80+ component variants, dark/light themes, typography scales, interactive micro-interaction prototypes, and clear tokens documentation ready for developer handoff.`,
    category: 'Design & Creative',
    budgetType: 'FIXED',
    budgetAmount: 2800,
    estimatedDuration: '3 weeks',
    deadline: new Date(Date.now() + 15 * 86400000).toISOString(),
    requiredSkills: ['UI/UX Design', 'Figma', 'Tailwind CSS'],
    status: 'OPEN',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    client: DEMO_USERS[2],
    _count: { proposals: 3 },
  }
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'proposal-1',
    jobId: 'job-1',
    freelancerId: 'user-freelancer-1',
    bidAmount: 4300,
    estimatedDuration: '4 weeks',
    coverLetter: `Hello Sarah,\n\nI reviewed your requirements for the AI Financial Copilot Dashboard. Having architected 3 similar production Next.js apps featuring Prisma ORM and streaming chat completions, I can deliver a blazing-fast, rock-solid solution.\n\nMy proposed milestones:\n1. Architecture setup, database schemas, authentication & role switcher\n2. Real-time telemetry dashboard & OpenAI streaming UI\n3. Final testing, performance optimization, and clean deployment\n\nLooking forward to collaborating!`,
    status: 'PENDING',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    freelancer: DEMO_USERS[1],
  },
  {
    id: 'proposal-2',
    jobId: 'job-2',
    freelancerId: 'user-freelancer-1',
    bidAmount: 3200,
    estimatedDuration: '2 weeks',
    coverLetter: `Hi Elena,\n\nI have extensive experience with Stripe Connect Custom and Express accounts, including escrow holds, transfer schedules, and automated webhook reconciliation. I will ensure complete compliance, webhook idempotency, and automated failure retries.`,
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    freelancer: DEMO_USERS[1],
  }
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'contract-1',
    jobId: 'job-2',
    proposalId: 'proposal-2',
    clientId: 'user-dual-1',
    freelancerId: 'user-freelancer-1',
    agreedAmount: 3200,
    status: 'ACTIVE',
    escrowStatus: 'HELD_IN_ESCROW',
    stripePaymentIntentId: 'pi_test_3O482928472918482049182',
    startDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    client: DEMO_USERS[2],
    freelancer: DEMO_USERS[1],
    job: INITIAL_JOBS[1],
    proposal: INITIAL_PROPOSALS[1],
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-client-1',
    type: 'PROPOSAL_RECEIVED',
    title: 'New proposal received',
    message: 'Alex Rivera submitted a proposal on "Full-Stack Next.js Developer for AI Copilot Dashboard"',
    link: '/jobs/job-1',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-freelancer-1',
    type: 'PROPOSAL_ACCEPTED',
    title: 'Proposal accepted & Escrow funded!',
    message: 'Elena Rostova accepted your proposal for "Stripe Connect Escrow Payment Gateway". $3,200 is secured in escrow.',
    link: '/contracts/contract-1',
    read: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  }
];
